### ISSUE TITLE
Is this currently functioning?

### ISSUE THREAD

**Issue by pnewell** [MatthewGCampbell/homebridge-molekule-air#1]
**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by MatthewGCampbell** [comment]
No it doesn't currently function, I made this project and then never got to actually coding it :).
